# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_call:

name: phs_document.yaml

permissions:
  contents: read
  pull-requests: read

jobs:
  phs_document:
    name: "Automatically re-build the package documentation"
    runs-on: ubuntu-latest
    container:
      image: rocker/r-ver
      
    permissions:
      contents: write
      pull-requests: write
      
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - name: Install git
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git
      
      - name: Mark workspace as safe for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        
      - name: Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref_name }}

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4
        with:
          extra-packages: |
            any::roxygen2
            any::desc

      - name: Normalise DESCRIPTION
        run: desc::desc_normalize()
        shell: Rscript {0}

      - name: Document
        run: roxygen2::roxygenise()
        shell: Rscript {0}

      - name: Commit and push changes
        id: commit_step_document
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "Document package (GHA)"
          commit_user_name: ${{ github.actor }}
          commit_user_email: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
        continue-on-error: true

      - name: Create Pull Request
        if: ${{ steps.commit_step_document.outputs.changes_detected == 'true' && steps.commit_step_document.outcome == 'failure' }}
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: "Document package (GHA)"
          branch: auto-document-code
          delete-branch: true
          title: "Document package (GHA)"
          labels: maintenance
          base: ${{ github.event.pull_request.base.ref }}
          body: |
            This Pull Request was automatically created to apply documentation changes to your code.
            Please review and merge this PR.
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
